# Generated by Django 5.2.8 on 2026-01-07 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Number of passengers', validators=[django.core.validators.MinValueValidator(1, 'Capacity must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Price must be greater than zero')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
