# Generated by Django 5.2.8 on 2026-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_client_email_alter_car_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
